# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    rust: "1.61"
  commands:
    - pip install pdoc
    - pdoc text_splitter -o $READTHEDOCS_OUTPUT/html/

python:
  install:
    - method: pip
      path: bindings/python
