# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    rust: "latest"
  commands:
    - pip install pdoc
    - cd ./bindings/python && pip install .
    - pdoc semantic_text_splitter -d google -o $READTHEDOCS_OUTPUT/html/
