name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read

jobs:
  release:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: stable
      - name: Publish to crates.io
        env:
          CRATES_IO_TOKEN: ${{secrets.CRATES_IO_TOKEN}}
        run: |
          cargo publish --token "${CRATES_IO_TOKEN}"
